# Generated by Django 4.2.11 on 2024-04-02 23:12

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=500)),
                ("data_inicio", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Ativo"), ("I", "Inativo")], max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["autor"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Cadastro de Categorias",
                "verbose_name_plural": "Cadastro de Categorias",
                "ordering": ["categoria"],
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "conteudo",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("data_publicacao", models.DateTimeField(auto_now_add=True)),
                ("imagem", models.ImageField(upload_to="uploads/noticias")),
                (
                    "id_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="noticia.autor"
                    ),
                ),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="noticia.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
                "ordering": ["-data_publicacao"],
            },
        ),
    ]
