# Generated by Django 4.2.11 on 2024-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noticia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="imagem",
            field=models.ImageField(default="default.jpg", upload_to="uploads/autores"),
        ),
    ]
