# Generated by Django 4.2.11 on 2024-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noticia", "0002_autor_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="imagem",
            field=models.FileField(upload_to="uploads/noticias"),
        ),
    ]
