# Generated by Django 4.2.11 on 2024-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=50)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("O", "Outros"),
                        ],
                        max_length=10,
                    ),
                ),
                ("usuario", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=75)),
                ("senha", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField(help_text="aaaa/dd/mm")),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Formulário de Cadastro",
                "verbose_name_plural": "Formulários de Cadastros",
                "ordering": ["-data_cadastro"],
            },
        ),
    ]
