# Generated by Django 4.2.11 on 2024-03-30 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastroUsuario", "0002_alter_cadastro_data_nascimento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cadastro",
            old_name="sexo",
            new_name="genero",
        ),
    ]
